# -*- coding: utf-8 -*-
"""thames_estuary_water_land_kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17G0RfJ_AHDh67fl-4waRuAW7Yn5cpKD9
"""

!pip install geemap earthengine-api -q

import ee
import geemap
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

ee.Authenticate()
ee.Initialize(project='geol0069-497923')

# Thames Estuary study area, UK
region = ee.Geometry.Rectangle([0.55, 51.40, 1.05, 51.65])

def get_sentinel2_composite(year, region):
    """
    Fetch Sentinel-2 Surface Reflectance imagery for summer months
    and create a median composite for the selected year.
    """

    start_date = f'{year}-06-01'
    end_date = f'{year}-09-30'

    collection = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
        .filterDate(start_date, end_date) \
        .filterBounds(region) \
        .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))

    print(f'{year} number of images:', collection.size().getInfo())

    image = collection.median().clip(region)

    return image

image_2020 = get_sentinel2_composite(2020, region)
image_2024 = get_sentinel2_composite(2024, region)

Map_rgb_2020 = geemap.Map()
Map_rgb_2020.centerObject(region, 10)

rgb_vis = {
    'bands': ['B4', 'B3', 'B2'],
    'min': 0,
    'max': 3000,
    'gamma': 1.3
}

Map_rgb_2020.addLayer(image_2020, rgb_vis, 'Sentinel-2 RGB 2020')
Map_rgb_2020

Map_rgb_2024 = geemap.Map()
Map_rgb_2024.centerObject(region, 10)

Map_rgb_2024.addLayer(image_2024, rgb_vis, 'Sentinel-2 RGB 2024')
Map_rgb_2024

# NDWI = (Green - NIR) / (Green + NIR)
# Sentinel-2: B3 = Green, B8 = Near Infrared

ndwi_2020 = image_2020.normalizedDifference(['B3', 'B8']).rename('NDWI')
ndwi_2024 = image_2024.normalizedDifference(['B3', 'B8']).rename('NDWI')

Map_ndwi_2020 = geemap.Map()
Map_ndwi_2020.centerObject(region, 10)

ndwi_vis = {
    'min': -0.5,
    'max': 0.5,
    'palette': ['brown', 'white', 'blue']
}

Map_ndwi_2020.addLayer(ndwi_2020, ndwi_vis, 'NDWI 2020')
Map_ndwi_2020

Map_ndwi_2024 = geemap.Map()
Map_ndwi_2024.centerObject(region, 10)

Map_ndwi_2024.addLayer(ndwi_2024, ndwi_vis, 'NDWI 2024')
Map_ndwi_2024

def get_water_mask_kmeans(ndwi, region, year):
    """
    Apply K-means clustering to NDWI image.
    The cluster with higher mean NDWI is interpreted as water.
    """

    # Sample NDWI pixels
    samples = ndwi.sample(
        region=region,
        scale=10,
        numPixels=5000,
        seed=42,
        geometries=False
    )

    # Train K-means with 2 clusters
    clusterer = ee.Clusterer.wekaKMeans(2).train(samples)

    # Apply clusterer to full NDWI image
    clustered = ndwi.cluster(clusterer)

    # Calculate mean NDWI for cluster 0
    mean_cluster_0 = ndwi.updateMask(clustered.eq(0)).reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=region,
        scale=10,
        maxPixels=1e9
    ).get('NDWI')

    # Calculate mean NDWI for cluster 1
    mean_cluster_1 = ndwi.updateMask(clustered.eq(1)).reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=region,
        scale=10,
        maxPixels=1e9
    ).get('NDWI')

    mean0 = ee.Number(mean_cluster_0)
    mean1 = ee.Number(mean_cluster_1)

    print(f'{year} mean NDWI cluster 0:', mean0.getInfo())
    print(f'{year} mean NDWI cluster 1:', mean1.getInfo())

    # Higher NDWI cluster is water
    water_cluster = ee.Number(ee.Algorithms.If(mean0.gt(mean1), 0, 1))

    water_mask = clustered.eq(water_cluster)
    land_mask = water_mask.Not()

    return water_mask, land_mask, clustered

water_2020, land_2020, clustered_2020 = get_water_mask_kmeans(ndwi_2020, region, 2020)
water_2024, land_2024, clustered_2024 = get_water_mask_kmeans(ndwi_2024, region, 2024)

Map_clusters_2020 = geemap.Map()
Map_clusters_2020.centerObject(region, 10)

Map_clusters_2020.addLayer(clustered_2020.randomVisualizer(), {}, 'K-means clusters 2020')
Map_clusters_2020

Map_clusters_2024 = geemap.Map()
Map_clusters_2024.centerObject(region, 10)

Map_clusters_2024.addLayer(clustered_2024.randomVisualizer(), {}, 'K-means clusters 2024')
Map_clusters_2024

Map_water_land_2020 = geemap.Map()
Map_water_land_2020.centerObject(region, 10)

Map_water_land_2020.addLayer(
    water_2020.updateMask(water_2020),
    {'palette': ['blue']},
    'Water 2020'
)

Map_water_land_2020.addLayer(
    land_2020.updateMask(land_2020),
    {'palette': ['green']},
    'Land 2020'
)

Map_water_land_2020

Map_water_land_2024 = geemap.Map()
Map_water_land_2024.centerObject(region, 10)

Map_water_land_2024.addLayer(
    water_2024.updateMask(water_2024),
    {'palette': ['blue']},
    'Water 2024'
)

Map_water_land_2024.addLayer(
    land_2024.updateMask(land_2024),
    {'palette': ['green']},
    'Land 2024'
)

Map_water_land_2024

threshold_water_2024 = ndwi_2024.gt(0)

Map_threshold_2024 = geemap.Map()
Map_threshold_2024.centerObject(region, 10)

Map_threshold_2024.addLayer(
    threshold_water_2024.updateMask(threshold_water_2024),
    {'palette': ['cyan']},
    'NDWI threshold water 2024'
)

Map_threshold_2024.addLayer(
    water_2024.updateMask(water_2024),
    {'palette': ['blue']},
    'K-means water 2024'
)

Map_threshold_2024

def calculate_area_km2(mask, region):
    """
    Calculate area of a binary mask in square kilometres.
    """

    area_image = ee.Image.pixelArea()

    area = area_image.updateMask(mask).reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=region,
        scale=10,
        maxPixels=1e9
    )

    area_km2 = ee.Number(area.get('area')).divide(1e6)

    return area_km2

water_area_2020 = calculate_area_km2(water_2020, region)
land_area_2020 = calculate_area_km2(land_2020, region)

water_area_2024 = calculate_area_km2(water_2024, region)
land_area_2024 = calculate_area_km2(land_2024, region)

print('Water area 2020 km²:', water_area_2020.getInfo())
print('Land area 2020 km²:', land_area_2020.getInfo())
print('Water area 2024 km²:', water_area_2024.getInfo())
print('Land area 2024 km²:', land_area_2024.getInfo())

water_difference = water_area_2024.subtract(water_area_2020)
print('Water area difference 2024 - 2020 km²:', water_difference.getInfo())

# Water gain: pixels that were not water in 2020 but are water in 2024
water_gain = water_2024.And(water_2020.Not())

# Water loss: pixels that were water in 2020 but are not water in 2024
water_loss = water_2020.And(water_2024.Not())

print("water_gain and water_loss have been created.")

task_gain = ee.batch.Export.image.toDrive(
    image=water_gain,
    description='Thames_Estuary_Water_Gain_2020_2024',
    folder='AI4EO_Project',
    fileNamePrefix='thames_estuary_water_gain_2020_2024',
    region=region,
    scale=10,
    maxPixels=1e9
)

task_loss = ee.batch.Export.image.toDrive(
    image=water_loss,
    description='Thames_Estuary_Water_Loss_2020_2024',
    folder='AI4EO_Project',
    fileNamePrefix='thames_estuary_water_loss_2020_2024',
    region=region,
    scale=10,
    maxPixels=1e9
)

task_gain.start()
task_loss.start()

print('Export tasks for water gain and water loss started.')

import geemap
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches

# Create classified image:
# 1 = water
# 2 = land
water_land_2024 = ee.Image(0) \
    .where(water_2024, 1) \
    .where(land_2024, 2) \
    .clip(region)

# Convert to numpy with lower resolution to avoid memory limit
arr_2024 = geemap.ee_to_numpy(
    water_land_2024,
    region=region,
    scale=50
)

if arr_2024.ndim == 3:
    arr_2024 = arr_2024[:, :, 0]

# Plot
cmap = ListedColormap(['blue', 'green'])

plt.figure(figsize=(7, 6))
plt.imshow(arr_2024, cmap=cmap, vmin=1, vmax=2)
plt.title('K-means Water-Land Classification (2024)', fontsize=14)
plt.xlabel('Pixel column')
plt.ylabel('Pixel row')

water_patch = mpatches.Patch(color='blue', label='Water')
land_patch = mpatches.Patch(color='green', label='Land')
plt.legend(handles=[water_patch, land_patch], loc='upper right')

plt.tight_layout()
plt.show()

import geemap
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches

# Create classified image: 1 = water, 2 = land
water_land_2020 = ee.Image(0) \
    .where(water_2020, 1) \
    .where(land_2020, 2) \
    .clip(region)

water_land_2024 = ee.Image(0) \
    .where(water_2024, 1) \
    .where(land_2024, 2) \
    .clip(region)

# Convert to numpy at lower resolution to avoid memory limit
arr_2020 = geemap.ee_to_numpy(water_land_2020, region=region, scale=50)
arr_2024 = geemap.ee_to_numpy(water_land_2024, region=region, scale=50)

if arr_2020.ndim == 3:
    arr_2020 = arr_2020[:, :, 0]

if arr_2024.ndim == 3:
    arr_2024 = arr_2024[:, :, 0]

# Colour map
cmap = ListedColormap(['blue', 'green'])

# Plot side-by-side
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

axes[0].imshow(arr_2020, cmap=cmap, vmin=1, vmax=2)
axes[0].set_title('K-means Water-Land Classification (2020)', fontsize=13)
axes[0].set_xlabel('Pixel column')
axes[0].set_ylabel('Pixel row')

axes[1].imshow(arr_2024, cmap=cmap, vmin=1, vmax=2)
axes[1].set_title('K-means Water-Land Classification (2024)', fontsize=13)
axes[1].set_xlabel('Pixel column')
axes[1].set_ylabel('Pixel row')

water_patch = mpatches.Patch(color='blue', label='Water')
land_patch = mpatches.Patch(color='green', label='Land')

fig.legend(
    handles=[water_patch, land_patch],
    title='Classes',
    loc='upper center',
    ncol=2
)

plt.tight_layout()

plt.savefig(
    '/content/drive/MyDrive/AI4EO_Project/kmeans_water_land_2020_2024_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# Water gain: non-water in 2020, water in 2024
water_gain = water_2024.And(water_2020.Not())

# Water loss: water in 2020, non-water in 2024
water_loss = water_2020.And(water_2024.Not())

# Create change map:
# 0 = no change / background
# 1 = water gain
# 2 = water loss
change_map = ee.Image(0) \
    .where(water_gain, 1) \
    .where(water_loss, 2) \
    .clip(region)

arr_change = geemap.ee_to_numpy(change_map, region=region, scale=50)

if arr_change.ndim == 3:
    arr_change = arr_change[:, :, 0]

change_cmap = ListedColormap(['white', 'blue', 'red'])

plt.figure(figsize=(8, 6))
plt.imshow(arr_change, cmap=change_cmap, vmin=0, vmax=2)

plt.title('Detected Water Extent Change (2020–2024)', fontsize=14)
plt.xlabel('Pixel column')
plt.ylabel('Pixel row')

nochange_patch = mpatches.Patch(color='white', label='No change / background')
gain_patch = mpatches.Patch(color='blue', label='Water gain')
loss_patch = mpatches.Patch(color='red', label='Water loss')

plt.legend(
    handles=[nochange_patch, gain_patch, loss_patch],
    title='Classes',
    loc='upper right'
)

plt.tight_layout()

plt.savefig(
    '/content/drive/MyDrive/AI4EO_Project/water_gain_loss_2020_2024.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

arr_ndwi_2024 = geemap.ee_to_numpy(ndwi_2024, region=region, scale=50)

if arr_ndwi_2024.ndim == 3:
    arr_ndwi_2024 = arr_ndwi_2024[:, :, 0]

plt.figure(figsize=(8, 6))
plt.imshow(arr_ndwi_2024, cmap='BrBG', vmin=-0.5, vmax=0.5)

plt.title('NDWI Map of the Thames Estuary (2024)', fontsize=14)
plt.xlabel('Pixel column')
plt.ylabel('Pixel row')

cbar = plt.colorbar()
cbar.set_label('NDWI value')

plt.tight_layout()

plt.savefig(
    '/content/drive/MyDrive/AI4EO_Project/ndwi_2024.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# Create NDWI threshold water mask
threshold_water_2024 = ndwi_2024.gt(0)

# Create image: 0 = background, 1 = NDWI threshold water, 2 = K-means water
comparison_map = ee.Image(0) \
    .where(threshold_water_2024, 1) \
    .where(water_2024, 2) \
    .clip(region)

arr_comparison = geemap.ee_to_numpy(comparison_map, region=region, scale=50)

if arr_comparison.ndim == 3:
    arr_comparison = arr_comparison[:, :, 0]

comparison_cmap = ListedColormap(['white', 'cyan', 'blue'])

plt.figure(figsize=(8, 6))
plt.imshow(arr_comparison, cmap=comparison_cmap, vmin=0, vmax=2)

plt.title('NDWI Threshold vs K-means Water Mask (2024)', fontsize=14)
plt.xlabel('Pixel column')
plt.ylabel('Pixel row')

background_patch = mpatches.Patch(color='white', label='Background / land')
threshold_patch = mpatches.Patch(color='cyan', label='NDWI threshold water')
kmeans_patch = mpatches.Patch(color='blue', label='K-means water')

plt.legend(
    handles=[background_patch, threshold_patch, kmeans_patch],
    title='Classes',
    loc='upper right'
)

plt.tight_layout()

plt.savefig(
    '/content/drive/MyDrive/AI4EO_Project/ndwi_threshold_vs_kmeans_2024.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# Select RGB bands and convert to numpy
rgb_2024 = image_2024.select(['B4', 'B3', 'B2']).clip(region)

arr_rgb_2024 = geemap.ee_to_numpy(rgb_2024, region=region, scale=50)

# Convert reflectance values for display
arr_rgb_2024 = arr_rgb_2024.astype(float)

# Simple stretch
arr_rgb_2024 = np.clip(arr_rgb_2024 / 3000, 0, 1)

plt.figure(figsize=(8, 6))
plt.imshow(arr_rgb_2024)

plt.title('Sentinel-2 RGB Composite of the Thames Estuary (2024)', fontsize=14)
plt.xlabel('Pixel column')
plt.ylabel('Pixel row')

plt.tight_layout()

plt.savefig(
    '/content/drive/MyDrive/AI4EO_Project/sentinel2_rgb_2024.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()